name: Pipeline
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant permission
        run: chmod +x gradlew
      - name: Run lint
        run: ./gradlew lintDebug
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant permission
        run: chmod +x gradlew
      - name: Run Test
        run: ./gradlew testDebugUnitTest
  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      output-name: ${{steps.publish.outputs.output1}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Java setup
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Grant permission
        run: chmod +x gradlew
      - name: Run Build
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: output share
        id: publish
        run: echo "output1 = some value" >> $GITHUB_OUTPUT
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app-debug
          path: apk/
      - name: Output contents
        run: |
          ls
          echo 'files from downloaded job'
      - name: Output shared
        run: echo "${{needs.build.outputs.output-name}}"
          
